<?php return array (
  'sans-serif' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold' => $rootDir . '/lib/fonts/ZapfDingbats',
    'italic' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold_italic' => $rootDir . '/lib/fonts/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '/lib/fonts/Symbol',
    'bold' => $rootDir . '/lib/fonts/Symbol',
    'italic' => $rootDir . '/lib/fonts/Symbol',
    'bold_italic' => $rootDir . '/lib/fonts/Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSans-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSans-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSans-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSansMono-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '/lib/fonts/DejaVuSerif-Italic',
    'normal' => $rootDir . '/lib/fonts/DejaVuSerif',
  ),
  'denk one' => array(
    'normal' => $fontDir . '/denk-one-normal_412726a95ebde6a6f83a4493935f76f1',
  ),
  'montserrat' => array(
    '100_italic' => $fontDir . '/montserrat-100-italic_5e7b5456cc27cbad497f54bc54a5638b',
    '200_italic' => $fontDir . '/montserrat-200-italic_698b7a25dc50b81299db81f74cb09e6c',
    '300_italic' => $fontDir . '/montserrat-300-italic_73cccc8de1f4cbfad4095ca5b43b780a',
    'italic' => $fontDir . '/montserrat-italic_f97fdad7586d43b36382df4a48d31137',
    '500_italic' => $fontDir . '/montserrat-500-italic_0514ce7eed319082b33e8abb8fc114eb',
    '600_italic' => $fontDir . '/montserrat-600-italic_c9db7dfc2613b76224b2d1263c273789',
    'bold_italic' => $fontDir . '/montserrat-bold-italic_24982c9819fd0140cf72d180e8bfcd02',
    '800_italic' => $fontDir . '/montserrat-800-italic_e3228621a5e28d83a8714995cba166c8',
    '900_italic' => $fontDir . '/montserrat-900-italic_a5d427707f0aade982139703942c7d10',
    '100' => $fontDir . '/montserrat-100_8f8d06bd7e6397c3a0ae1319e680222d',
    '200' => $fontDir . '/montserrat-200_fcac991cd4e3c0cc6e7264befc6f212a',
    '300' => $fontDir . '/montserrat-300_831e4a2ddf9ce3293b008f5af4a90307',
    'normal' => $fontDir . '/montserrat-normal_1670712df2f5748882e4babc80289e6c',
    '500' => $fontDir . '/montserrat-500_130de56681c1e5fa8e23de736b04156d',
    '600' => $fontDir . '/montserrat-600_c72c739b588e3b0a91b94e5fa082ca13',
    'bold' => $fontDir . '/montserrat-bold_d2ee9019f68278432acfd2b2308dd0d6',
    '800' => $fontDir . '/montserrat-800_32374a7d105921d089070025440b98dc',
    '900' => $fontDir . '/montserrat-900_29f14d7d0c5a9392f6bc17e008c657d0',
  ),
) ?>